<a href="https://colab.research.google.com/github/clinton-mwachia/Deep-Learning/blob/master/Fashion_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from __future__ import print_function
from keras.models import load_model
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
import numpy as np

batch_size = 128
num_classes = 10
epochs = 10

In [ ]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

print('shape of the train data is {}'.format(x_train.shape))
print('shape of the test data is {}'.format(x_test.shape))

# Flattening 
x_train = x_train.reshape(60000, 784).astype('float32')
x_test = x_test.reshape(10000, 784).astype('float32')

print('shape of the train data after reshape is {}'.format(x_train.shape))
print('shape of the test data after reshape is {}'.format(x_test.shape))


In [16]:
print(x_train.max()) ; print(x_train.min())
print(x_test.max()) ; print(x_test.min())

print(y_train)
print(y_test)

255.0
0.0
255.0
0.0
[9 0 0 ... 3 0 5]
[9 2 1 ... 8 1 5]


In [17]:
# Normalization
x_train = (x_train - np.mean(x_train)) / np.std(x_train)
x_test = (x_test - np.mean(x_test)) / np.std(x_test)

y_train = keras.utils.to_categorical(y_train, num_classes=num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes=num_classes)

print(x_train.max()) ; print(x_train.min())
print(x_test.max()) ; print(x_test.min())

print(y_train)
print(y_test)

2.0224075
-0.8102582
2.0234427
-0.81388575
[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(784,)))
model.add(Dropout(0.4))
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes,activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 256)               200960    
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 512)               131584    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                5130      
Total params: 337,674
Trainable params: 337,674
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

model.fit(x=x_train, y=y_train, batch_size=batch_size,
          epochs=epochs,
          validation_data=(x_test,y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 6s 93us/step - loss: 0.3856 - accuracy: 0.8595 - val_loss: 0.3775 - val_accuracy: 0.8644
Epoch 2/10
60000/60000 [==============================] - 5s 90us/step - loss: 0.3605 - accuracy: 0.8666 - val_loss: 0.3539 - val_accuracy: 0.8687
Epoch 3/10
60000/60000 [==============================] - 5s 90us/step - loss: 0.3441 - accuracy: 0.8727 - val_loss: 0.3499 - val_accuracy: 0.8716
Epoch 4/10
60000/60000 [==============================] - 5s 89us/step - loss: 0.3280 - accuracy: 0.8779 - val_loss: 0.3427 - val_accuracy: 0.8784
Epoch 5/10
60000/60000 [==============================] - 5s 89us/step - loss: 0.3154 - accuracy: 0.8823 - val_loss: 0.3379 - val_accuracy: 0.8762
Epoch 6/10
60000/60000 [==============================] - 5s 90us/step - loss: 0.3093 - accuracy: 0.8856 - val_loss: 0.3270 - val_accuracy: 0.8815
Epoch 7/10
60000/60000 [==============================] - 5s 90us/st

In [22]:
model.save('my_model.h5')

In [24]:
score = model.evaluate(x_test, y_test, verbose=1)
print('Test loss: ', score[0] * 100)
print('Test accuracy :', score[1] * 100)

10000/10000 [==============================] - 0s 45us/step
Test loss:  32.08529007434845
Test accuracy : 88.41999769210815
